# =========================================================
# Generated by DogeshBangla Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

age = int(17)
if (age >= 18):
    print("You can vote!")
else:
    print("You are too young to vote.")

