# =========================================================
# Generated by DogeshBangla Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

radius = float(5.5)
pi = float(3.1416)
area = float(((pi * radius) * radius))
print("Area of the circle:")
print(area)
