# =========================================================
# Generated by DogeshBangla Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

timer = int(5)
print("Countdown started:")
while (timer > 0):
    print(timer)
    timer = (timer - 1)

print("Boom!")
