# =========================================================
# Generated by DogeshBangla Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

target = int(5)
result = int(1)
count = int(1)
while (count <= target):
    result = (result * count)
    count = (count + 1)

print("Factorial of 5 is:")
print(result)
