# =========================================================
# Generated by DogeshBangla Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

a = int(0)
b = int(1)
temp = int(0)
count = int(0)
print("First 8 Fibonacci numbers:")
while (count < 8):
    print(a)
    temp = (a + b)
    a = b
    b = temp
    count = (count + 1)

