# =========================================================
# Generated by DogeshBangla Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("Hello, DogeshBangla!")
