# =========================================================
# Generated by DogeshBangla Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

a = int(10)
b = int(5)
result = int((a + (b * 2)))
print("Result is:")
print(result)
