# =========================================================
# Generated by DogeshBangla Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

number = int((-5))
if (number > 0):
    print("Number is Positive")
else:
    if (number < 0):
        print("Number is Negative")
    else:
        print("Number is Zero")
    

