# =========================================================
# Generated by DogeshBangla Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

n = int(10)
sum = int(0)
i = int(1)
while (i <= n):
    sum = (sum + i)
    i = (i + 1)

print("Sum of 1 to 10 is:")
print(sum)
