# =========================================================
# Generated by DogeshBangla Compiler v1.0
# CSE-4114 Compiler Design and Construction Sessional
# =========================================================
import sys
sys.stdout.reconfigure(encoding='utf-8')

x = int(10)
y = int(20)
x = (x + y)
y = (x - y)
x = (x - y)
print("Swapped Values (x then y):")
print(x)
print(y)
