// =============================================================
//  DogeshBangla Compiler — codegen.cpp
//  Full Python code generator implementation
//  CSE-4114 Compiler Design and Construction Sessional
// =============================================================
#include "codegen.h"
#include <stdexcept>
#include <iomanip>

CodeGenerator::CodeGenerator(ErrorHandler& errHandler)
    : err(errHandler), indentLevel(0) {}

// ------------------------------------------------------------------
// generate() — entry point, returns full Python source as a string
// ------------------------------------------------------------------
std::string CodeGenerator::generate(ProgramNode* program) {
    out.str("");
    out.clear();
    indentLevel = 0;

    // File header comment
    emitLine("# =========================================================");
    emitLine("# Generated by DogeshBangla Compiler v1.0");
    emitLine("# CSE-4114 Compiler Design and Construction Sessional");
    emitLine("# =========================================================");
    emitLine("import sys");
    emitLine("sys.stdout.reconfigure(encoding='utf-8')");
    emitLine("");

    for (auto& stmt : program->statements) {
        genStatement(stmt.get());
    }

    return out.str();
}

// ------------------------------------------------------------------
// Emit helpers
// ------------------------------------------------------------------
std::string CodeGenerator::getIndent() const {
    return std::string(indentLevel * 4, ' ');
}

void CodeGenerator::emit(const std::string& code) {
    out << code;
}

void CodeGenerator::emitLine(const std::string& line) {
    out << getIndent() << line << "\n";
}

void CodeGenerator::indent()  { indentLevel++; }
void CodeGenerator::dedent()  { if (indentLevel > 0) indentLevel--; }

// ------------------------------------------------------------------
// genStatement — dispatch to correct generator
// ------------------------------------------------------------------
void CodeGenerator::genStatement(ASTNode* node) {
    if (!node) return;

    if (auto* d = dynamic_cast<DeclarationNode*>(node))  { genDeclaration(d); return; }
    if (auto* a = dynamic_cast<AssignmentNode*>(node))   { genAssignment(a);  return; }
    if (auto* i = dynamic_cast<IfNode*>(node))           { genIf(i);          return; }
    if (auto* w = dynamic_cast<WhileNode*>(node))        { genWhile(w);       return; }
    if (auto* p = dynamic_cast<PrintNode*>(node))        { genPrint(p);       return; }
    if (auto* b = dynamic_cast<BlockNode*>(node))        { genBlock(b);       return; }

    err.semanticError(node->line, node->col,
        "Code generation: unknown AST node: " + node->nodeType());
}

// ------------------------------------------------------------------
// genBlock — generate all statements inside a block (no braces in Python)
// ------------------------------------------------------------------
void CodeGenerator::genBlock(BlockNode* node) {
    for (auto& stmt : node->statements) {
        genStatement(stmt.get());
    }
}

// ------------------------------------------------------------------
// genDeclaration — dhoro sankhya x = 5  →  x = int(5)
// ------------------------------------------------------------------
void CodeGenerator::genDeclaration(DeclarationNode* node) {
    std::string pyExpr = genExpr(node->initializer.get());
    std::string typeStr = (node->type == DataType::SANKHYA) ? "int" : "float";

    // Emit:  x = int(expr)  or  x = float(expr)
    emitLine(node->name + " = " + typeStr + "(" + pyExpr + ")");
}

// ------------------------------------------------------------------
// genAssignment — x = expr  →  x = expr
// ------------------------------------------------------------------
void CodeGenerator::genAssignment(AssignmentNode* node) {
    std::string pyExpr = genExpr(node->value.get());
    emitLine(node->name + " = " + pyExpr);
}

// ------------------------------------------------------------------
// genIf — jodi (cond) block [nahole block]
// ------------------------------------------------------------------
void CodeGenerator::genIf(IfNode* node) {
    std::string condStr = genExpr(node->condition.get());
    emitLine("if " + condStr + ":");
    indent();
    if (auto* b = dynamic_cast<BlockNode*>(node->thenBlock.get())) {
        if (b->statements.empty()) {
            emitLine("pass");
        } else {
            genBlock(b);
        }
    }
    dedent();

    if (node->elseBlock) {
        emitLine("else:");
        indent();
        if (auto* b = dynamic_cast<BlockNode*>(node->elseBlock.get())) {
            if (b->statements.empty()) {
                emitLine("pass");
            } else {
                genBlock(b);
            }
        }
        dedent();
    }
    emitLine("");
}

// ------------------------------------------------------------------
// genWhile — jotokhon (cond) block
// ------------------------------------------------------------------
void CodeGenerator::genWhile(WhileNode* node) {
    std::string condStr = genExpr(node->condition.get());
    emitLine("while " + condStr + ":");
    indent();
    if (auto* b = dynamic_cast<BlockNode*>(node->body.get())) {
        if (b->statements.empty()) {
            emitLine("pass");
        } else {
            genBlock(b);
        }
    }
    dedent();
    emitLine("");
}

// ------------------------------------------------------------------
// genPrint — dekhao expr  →  print(expr)
// ------------------------------------------------------------------
void CodeGenerator::genPrint(PrintNode* node) {
    std::string pyExpr = genExpr(node->expr.get());
    emitLine("print(" + pyExpr + ")");
}

// ══════════════════════════════════════════════════════════════════
//  Expression code generation
// ══════════════════════════════════════════════════════════════════

std::string CodeGenerator::genExpr(ASTNode* node) {
    if (!node) return "None";

    // Integer literal
    if (auto* n = dynamic_cast<IntLiteralNode*>(node)) {
        return std::to_string(n->value);
    }

    // Float literal
    if (auto* n = dynamic_cast<FloatLiteralNode*>(node)) {
        std::ostringstream ss;
        ss << std::fixed << std::setprecision(6) << n->value;
        // Remove trailing zeros
        std::string s = ss.str();
        size_t dot = s.find('.');
        if (dot != std::string::npos) {
            size_t last = s.find_last_not_of('0');
            if (last == dot) last++;
            s = s.substr(0, last + 1);
        }
        return s;
    }

    // String literal
    if (auto* n = dynamic_cast<StringLiteralNode*>(node)) {
        return "\"" + n->value + "\"";
    }

    // Identifier
    if (auto* n = dynamic_cast<IdentifierNode*>(node)) {
        return n->name;
    }

    // Binary operation
    if (auto* n = dynamic_cast<BinaryOpNode*>(node)) {
        return genBinaryOp(n);
    }

    // Unary minus
    if (auto* n = dynamic_cast<UnaryMinusNode*>(node)) {
        return genUnaryMinus(n);
    }

    err.semanticError(node->line, node->col,
        "Code generation: unknown expression node: " + node->nodeType());
    return "None";
}

std::string CodeGenerator::genBinaryOp(BinaryOpNode* node) {
    std::string left  = genExpr(node->left.get());
    std::string right = genExpr(node->right.get());
    std::string op    = opToString(node->op);

    // Wrap in parentheses to preserve precedence
    return "(" + left + " " + op + " " + right + ")";
}

std::string CodeGenerator::genUnaryMinus(UnaryMinusNode* node) {
    return "(-" + genExpr(node->operand.get()) + ")";
}

std::string CodeGenerator::opToString(TokenType op) {
    switch (op) {
        case TokenType::PLUS:  return "+";
        case TokenType::MINUS: return "-";
        case TokenType::STAR:  return "*";
        case TokenType::SLASH: return "/";
        case TokenType::EQ:    return "==";
        case TokenType::NEQ:   return "!=";
        case TokenType::LT:    return "<";
        case TokenType::GT:    return ">";
        case TokenType::LEQ:   return "<=";
        case TokenType::GEQ:   return ">=";
        default:               return "?";
    }
}
